name: Run PRD docker

on:
  workflow_dispatch:
jobs:
  Production:
    runs-on: ubuntu-latest
    steps:
      - name: Production
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            sudo docker stop ${{ vars.DOCKER_NAME }}
            sudo docker rm ${{ vars.DOCKER_NAME }}
            sudo docker run -dp 10300:8080 --name ${{ vars.DOCKER_NAME }} --mount type=bind,source="$(pwd)"/config/prd.core.env.yaml,target=/app/.env.yaml ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.DOCKER_NAME }}
