name: Run UAT docker

on:
  workflow_dispatch:
env:
  PORT: "11300"
  DOCKER_NAME: "merchant"
jobs:
  UAT:
    runs-on: ubuntu-latest
    steps:
      - name: Update docker
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_NAME }}
            sudo docker stop ${{ env.DOCKER_NAME }}-uat
            sudo docker rm ${{ env.DOCKER_NAME }}-uat
            sudo docker run -dp ${{env.PORT}}:8080 --name ${{ env.DOCKER_NAME }}-uat --mount type=bind,source="$(pwd)"/config/uat.core.env.yaml,target=/app/.env.yaml ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_NAME }}
